apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-svc
  labels:
    app:nginx-deployment
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30090
  selector:
    app: nginx-deployment
